backend:
  name: git-gateway
  branch: main

media_folder: "img" # Où seront stockées les photos de sport
public_folder: "/img"

collections:
  - name: "blog"
    label: "Articles de Sport"
    folder: "blog" # Les articles seront créés dans un dossier /blog
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image de couverture", name: "image", widget: "image"}
      - {label: "Contenu de l'article", name: "body", widget: "markdown"}
