backend:
  name: github
  repo: sergiosveve-ctrl/blog-sport-togo
  branch: main
  base_url: https://blog-sport-togo.footpulse.workers.dev
  auth_endpoint: /auth

media_folder: "img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Articles de Sport"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image de couverture", name: "image", widget: "image"}
      - {label: "Contenu de l'article", name: "body", widget: "markdown"}
